Algoritmo "exercico 8"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo
// Data atual  : 03/09/2022
Var
// Seção de Declarações das variáveis 
litros_usados:inteiro
tempo:inteiro
velocidade:inteiro
distancia:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("")


Fimalgoritmo